export enum ModalType {
  ADD_TRANSACTION = "ADD_TRANSACTION",
  DELETE_TRANSACTION = "DELETE_TRANSACTION",
  ADD_WALLET = "ADD_WALLET",
  DELETE_WALLET = "DELETE_WALLET",
  DELETE_ACCOUNT = "DELETE_ACCOUNT",
}
